development:
  adapter: mysql
  database: gamerankr_dev
  username: gamerankr
  password: pass

test:
  adapter: mysql
  database: gamerankr_test
  username: gamerankr
  password: pass

production:
  adapter: mysql
  database: gamerankr_prod
  username: gamerankr
  password: pass
